//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseSentinel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class albara
    {
        public albara()
        {
            this.liniaalbara = new HashSet<liniaalbara>();
        }
    
        public int codi { get; set; }
        public Nullable<System.DateTime> dataAlbara { get; set; }
        public Nullable<System.DateTime> dataEntrega { get; set; }
        public int Comanda_codi { get; set; }
        public string Comanda_Client_CIF { get; set; }
        public int Comanda_Client_Contacte_id { get; set; }
    
        public virtual comanda comanda { get; set; }
        public virtual ICollection<liniaalbara> liniaalbara { get; set; }
    }
}
