//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseSentinel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class client
    {
        public client()
        {
            this.comanda = new HashSet<comanda>();
            this.contacte = new HashSet<contacte>();
        }
    
        public string CIF { get; set; }
        public string nom { get; set; }
        public string cognom { get; set; }
        public string adreça { get; set; }
        public string codiPostal { get; set; }
        public string pais { get; set; }
        public Nullable<bool> actiu { get; set; }
    
        public virtual ICollection<comanda> comanda { get; set; }
        public virtual ICollection<contacte> contacte { get; set; }
    }
}
