//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseSentinel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class liniacomanda
    {
        public int id { get; set; }
        public Nullable<double> preuKg { get; set; }
        public Nullable<int> quantitat { get; set; }
        public int Comanda_codi { get; set; }
        public string Comanda_Client_CIF { get; set; }
        public int Comanda_Client_Contacte_id { get; set; }
        public int Producte_id { get; set; }
    
        public virtual comanda comanda { get; set; }
        public virtual producte producte { get; set; }
    }
}
