//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseSentinel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class producte
    {
        public producte()
        {
            this.liniacomanda = new HashSet<liniacomanda>();
        }
    
        public int id { get; set; }
        public string nom { get; set; }
        public Nullable<double> preuKg { get; set; }
        public Nullable<int> unitatCaixa { get; set; }
        public string EAN13 { get; set; }
    
        public virtual ICollection<liniacomanda> liniacomanda { get; set; }
    }
}
